# Generated by Django 2.2 on 2020-09-19 21:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_master', '0003_auto_20200916_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo'),
        ),
    ]
